
name: armTemplateDeployment


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:

    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment sub create --location "UK South" --template-file ./arm-templates/resourcegroup.json

